In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
import pandas as pd

data = {
    'emp_id': [1,2,3,4,5,6,7,8],
    'emp_name': ['Amit','Neha','Ravi','Priya','Karan','Anjali','Suresh','Pooja'],
    'department': ['HR','IT','Finance','IT','HR','Finance','IT','HR'],
    'gender': ['Male','Female','Male','Female','Male','Female','Male','Female'],
    'education': ['Graduate','Postgraduate','Graduate','PhD','Postgraduate','Graduate','Graduate','PhD'],
    'city': ['Delhi','Mumbai','Pune','Delhi','Mumbai','Pune','Delhi','Mumbai'],
    'salary': [40000,60000,50000,80000,45000,52000,70000,48000],
    'experience': [2,5,3,6,1,4,8,9]
}

df = pd.DataFrame(data)
print(df)

   emp_id emp_name department  gender     education    city  salary  \
0       1     Amit         HR    Male      Graduate   Delhi   40000
1       2     Neha         IT  Female  Postgraduate  Mumbai   60000
2       3     Ravi    Finance    Male      Graduate    Pune   50000
3       4    Priya         IT  Female           PhD   Delhi   80000
4       5    Karan         HR    Male  Postgraduate  Mumbai   45000
5       6   Anjali    Finance  Female      Graduate    Pune   52000
6       7   Suresh         IT    Male      Graduate   Delhi   70000
7       8    Pooja         HR  Female           PhD  Mumbai   48000

   experience
0           2
1           5
2           3
3           6
4           1
5           4
6           8
7           9

In [8]:
one_hotencode=pd.get_dummies(df['gender'],dtype=int,drop_first=True)
one_hotencode

   Male
0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0

In [22]:
#using sklearn
from sklearn.preprocessing import OneHotEncoder
he=OneHotEncoder()
new_encoding=he.fit_transform(df[['gender']])
data=new_encoding.toarray()
df['encode_gender']=data[:,0]

In [31]:
#label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['department']=le.fit_transform(df['department'])

In [32]:
df

   emp_id emp_name  department  gender     education    city  salary
0       1     Amit           1    Male      Graduate   Delhi   40000
1       2     Neha           2  Female  Postgraduate  Mumbai   60000
2       3     Ravi           0    Male      Graduate    Pune   50000
3       4    Priya           2  Female           PhD   Delhi   80000
4       5    Karan           1    Male  Postgraduate  Mumbai   45000
5       6   Anjali           0  Female      Graduate    Pune   52000
6       7   Suresh           2    Male      Graduate   Delhi   70000
7       8    Pooja           1  Female           PhD  Mumbai   48000

In [36]:
#ordinal encoding
from sklearn.preprocessing import OrdinalEncoder
ord_enc=OrdinalEncoder()
df['education']=ord_enc.fit_transform(df[['education']])
df

   emp_id emp_name department  gender  education    city  salary  experience
0       1     Amit         HR    Male        0.0   Delhi   40000           2
1       2     Neha         IT  Female        2.0  Mumbai   60000           5
2       3     Ravi    Finance    Male        0.0    Pune   50000           3
3       4    Priya         IT  Female        1.0   Delhi   80000           6
4       5    Karan         HR    Male        2.0  Mumbai   45000           1
5       6   Anjali    Finance  Female        0.0    Pune   52000           4
6       7   Suresh         IT    Male        0.0   Delhi   70000           8
7       8    Pooja         HR  Female        1.0  Mumbai   48000           9

In [37]:
#linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
x=df['experience']
y=df['salary']
x=x.values.reshape(-1,1)
lr.fit(x,y)

LinearRegression()

In [38]:
lr.predict([[5]])

array([56261.26126126])

In [39]:
#how to use multilinear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
x=df[['experience','education']]
y=df['salary']
lr.fit(x,y)

LinearRegression()

In [44]:
lr.predict([[5,0.0]])
import numpy as np

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [45]:
#how to handle misssion records
import pandas as pd

data = {
    'emp_id': [1,2,3,4,5,6,7,8],
    'emp_name': ['Amit','Neha','Ravi','Priya','Karan','Anjali','Suresh','Pooja'],
    'department': ['HR',np.nan,'Finance','IT','HR','Finance','IT','HR'],
    'gender': ['Male','Female','Male','Female','Male','Female','Male','Female'],
    'education': ['Graduate','Postgraduate','Graduate','PhD','Postgraduate','Graduate','Graduate','PhD'],
    'city': ['Delhi','Mumbai','Pune','Delhi','Mumbai','Pune','Delhi','Mumbai'],
    'salary': [40000,np.nan,50000,80000,45000,52000,70000,48000],
    'experience': [2,5,3,6,1,4,8,9]
}

df = pd.DataFrame(data)
print(df)

   emp_id emp_name department  gender     education    city  salary  \
0       1     Amit         HR    Male      Graduate   Delhi   40000
1       2     Neha        NaN  Female  Postgraduate  Mumbai   60000
2       3     Ravi    Finance    Male      Graduate    Pune   50000
3       4    Priya         IT  Female           PhD   Delhi   80000
4       5    Karan         HR    Male  Postgraduate  Mumbai   45000
5       6   Anjali    Finance  Female      Graduate    Pune   52000
6       7   Suresh         IT    Male      Graduate   Delhi   70000
7       8    Pooja         HR  Female           PhD  Mumbai   48000

   experience
0           2
1           5
2           3
3           6
4           1
5           4
6           8
7           9

In [66]:
n=df['department'].mode()[0]
for i in range(len(df['department'])):
    x=df['department'].isnull()
    if x[i]==True:
        df['department'][i]=n

# df['department'].isnull()

/tmp/ipykernel_442/1763127461.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['department'][i]=n
/tmp/ipykernel_442/1763127461.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['department'][i]=n

In [67]:
df

,emp_id,emp_name,department,gender,education,city,salary,experience
0,1,Amit,HR,Male,Graduate,Delhi,40000.0,2
1,2,Neha,HR,Female,Postgraduate,Mumbai,60000.0,5
2,3,Ravi,Finance,Male,Graduate,Pune,NaN,3
3,4,Priya,IT,Female,PhD,Delhi,80000.0,6
4,5,Karan,HR,Male,Postgraduate,Mumbai,45000.0,1
5,6,Anjali,Finance,Female,Graduate,Pune,52000.0,4
6,7,Suresh,IT,Male,Graduate,Delhi,70000.0,8
7,8,Pooja,HR,Female,PhD,Mumbai,48000.0,9

In [70]:
df['salary'].fillna(df['salary'].mean(),inplace=True)
df

/tmp/ipykernel_442/922588880.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary'].fillna(df['salary'].mean(),inplace=True)

,emp_id,emp_name,department,gender,education,city,salary,experience
0,1,Amit,HR,Male,Graduate,Delhi,40000.000000,2
1,2,Neha,HR,Female,Postgraduate,Mumbai,60000.000000,5
2,3,Ravi,Finance,Male,Graduate,Pune,56428.571429,3
3,4,Priya,IT,Female,PhD,Delhi,80000.000000,6
4,5,Karan,HR,Male,Postgraduate,Mumbai,45000.000000,1
5,6,Anjali,Finance,Female,Graduate,Pune,52000.000000,4
6,7,Suresh,IT,Male,Graduate,Delhi,70000.000000,8
7,8,Pooja,HR,Female,PhD,Mumbai,48000.000000,9